[env:seeed_xiao_esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = partitions/huge_app.csv
monitor_speed = 115200

lib_deps =
    https://github.com/SwiCago/HeatPump.git
    mathieucarbou/AsyncTCP
    mathieucarbou/ESPAsyncWebServer
    knolleary/PubSubClient
    bblanchon/ArduinoJson

lib_ignore =
    WebServer

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DASYNC_TCP_SSL_ENABLED=0
    -DCONFIG_ESP_MATTER_ENABLE_DATA_MODEL=1

extra_scripts =
    pre:scripts/load_env.py
    pre:scripts/gzip_ui.py

custom_dotenv_path         = ${PROJECT_DIR}/.env
custom_dotenv_example_path = ${PROJECT_DIR}/.env.example

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
board_build.partitions = partitions/huge_app.csv
monitor_speed = 115200

lib_deps =
    https://github.com/SwiCago/HeatPump.git
    mathieucarbou/AsyncTCP
    mathieucarbou/ESPAsyncWebServer
    knolleary/PubSubClient
    bblanchon/ArduinoJson

lib_ignore =
    WebServer

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DASYNC_TCP_SSL_ENABLED=0
    -DCONFIG_ESP_MATTER_ENABLE_DATA_MODEL=1

extra_scripts =
    pre:scripts/load_env.py
    pre:scripts/gzip_ui.py

custom_dotenv_path         = ${PROJECT_DIR}/.env
custom_dotenv_example_path = ${PROJECT_DIR}/.env.example
